# Generated by Django 5.1.4 on 2024-12-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0002_dish'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='category',
            field=models.CharField(choices=[('drink', 'Напиток'), ('main', 'Основное блюдо'), ('dessert', 'Десерт'), ('appetizer', 'Закуска')], default='main', max_length=20),
        ),
    ]
